ovmf: Fix build with GCC 16 and GLIBC 2.43
Backport two patches from master to fix native build with
GCC 16 and GLIBC 2.43

commit 3597306191297b504683b83fe7750e49c6a2e836
Author: Gerd Hoffmann <kraxel@redhat.com>
Date:   Thu Jan 29 09:23:32 2026 +0100

    BaseTools/StringFuncs: fix gcc 16 warning

    StringFuncs.c: In function ‘SplitStringByWhitespace’:
    StringFuncs.c:113:15: error: variable ‘Item’ set but not used [-Werror=unused-but-set-variable=]
      113 |   UINTN       Item;
          |               ^~~~

    Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>

Author: Gerd Hoffmann <kraxel@redhat.com>
Date:   Mon Dec 8 10:28:50 2025 +0100

    BaseTools/EfiRom: fix compiler warning

    New warning after updating gcc:

    EfiRom.c: In function ‘main’:
    EfiRom.c:78:17: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]

    The assigned value is not used, so fix the warning by just removing it.

    Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>