externalsrc.bbclass: Backport some changes
Backported a combination of these commits:

commit 66ff3d1f65cd2e7f5319e98fa41f47a59b714c72
Author: Peter Marko <peter.marko@siemens.com>
Date:   Thu Dec 1 15:04:40 2022 +0100

    externalsrc: fix lookup for .gitmodules

    Commit 0533edac277080e1bd130c14df0cbac61ba01a0c broke
    bitbake parsing when bitbake is executed from directory with existing .gitmodules
    and the recipe in externalsrc does not have .gitmodules

    The check needs to search for .gitmodules in sources path, not cwd.

    iParsing recipes...ERROR: ExpansionError during parsing <path to recipe>
    ...
    bb.data_smart.ExpansionError: Failure expanding variable do_compile[file-checksums], expression was ${@srctree_hash_files(d)} which triggered exception CalledProcessError: Command '['git', 'config', '--file', '.gitmodules', '--get-regexp', 'path']' returned non-zero exit status 1.

    Signed-off-by: Peter Marko <peter.marko@siemens.com>
    Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>

commit b4f0f7c4934bade9e4d4a1086f9d8b29d8e9ad45
Author: Thomas Roos <throos@amazon.de>
Date:   Mon Jan 16 15:30:22 2023 +0100

    devtool: fix devtool finish when gitmodules file is empty

    When a .gitmodules file exists but is empty then devtool finish fails.
    Add an additional check for this.

    [YOCTO #14999]

    Signed-off-by: Thomas Roos <throos@amazon.de>
    Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

and a few others.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>